### ISSUE TITLE
Using includeDirByFlag is causing runtime errors after Ember 3.4 upgrade

### ISSUE THREAD

**Issue by kiwi-josh** [minichate/ember-cli-conditional-compile#59] opened 2019-03-07 03:16 UTC
This is my config in `environment/config.js`

```
featureFlags: {
  WEBSITE_BUILD: isWebBuild,
  NATIVE_BUILD: isNativeBuild
},
includeDirByFlag: {
  WEBSITE_BUILD: [
    /components\/website-only/,
    /routes\/website-only/,
    /controllers\/website-only/,
    /templates\/website-only/
  ],
  NATIVE_BUILD: [
    /components\/native-only/,
    /routes\/native-only/,
    /controllers\/native-only/,
    /templates\/native-only/
  ]
}
```

On Ember `2.16` up to Ember `3.1.4`, the above config worked.

However I have just tried upgrading to Ember `3.4.4` we are getting this error in the console:
`Uncaught SyntaxError: Unexpected identifier`

This is the output if I do a compiled build with `isWebBuild` true and `isNativeBuild` false using this command: `ember build --environment=production`

```
...
define("bookings/controllers/modal-loading",["exports"],function(e){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
var t=Ember.Controller.extend({platform:Ember.inject.service(),isNativeBuild:Ember.computed.readOnly("platform.isNativeBuild")})
e.default=t})
import Controller from"@ember/controller"
import{inject as service}from"@ember/service"
import{readOnly}from"@ember/object/computed"
export default Controller.extend({platform:service(),hi:"appleapple",nativeAppVersion:readOnly("platform.nativeAppVersion")})
define("bookings/controllers/suburb/clinic",["exports"],function(e){Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
var t=Ember.Controller.extend({queryParams:["top"],firstDoctorSlug:void 0})
e.default=t}),define(...
```

As you can see, there was a controller called `controllers/native-only/whats-new.js` that should have been stripped from the output. However only the `define` wrapping function has been stripped, leaving the "guts" of the controller still in the source code and throwing errors.

If I comment out `includeDirByFlag` config, the build works again.
Please note I am running this version: `"ember-cli-conditional-compile": "^1.1.1"`

**Comment by wytlytningNZ** [comment] 2019-03-08 00:48
Update: It seems as though the conditional compiling works if I update route/controller/component in question to an ES6 class 🤔 

Is this expected behaviour?

**Comment by lozjackson** [comment] 2019-03-10 17:29
I have found this also.. If I use a version of Ember-cli >= 3.4 then the `ember-cli-conditional-compile-features` initialiser gets included in the production output:

```js
...e.default=a})
import Ember from"ember"
var initializer={name:"ember-cli-conditional-compile-features",initialize:function(e){Ember.Logger.info("Initializing feature flags")}},feature_flags=EMBER_CLI_CONDITIONAL_COMPILE_INJECTIONS
Object.keys(feature_flags).map(function(e){window[e]=feature_flags[e]})
export default initializer
define(...
```

This causes an error `Uncaught SyntaxError: Unexpected identifier`.

Also, to add to this, If I use a version of ember-cli-conditional-compile >= 1.1.0, then the `enableCompile` property in the `ember-cli-conditional-compile/index.js` file is `undefined` resulting in the initializer being included in the output with the feature flags baked in.  This means the feature flags are also added to the `window` object in production.

**Comment by halfbyte** [comment] 2019-05-03 09:20
After lots of debugging last night, I think I found the cause of this error. The way the compiling has been reorganized for Ember 3.4 pushed a lot of code from `broccoli/ember-app.js` to `broccoli/default-packager.js` and in the process, we ended up with this new `[processAppAndDependencies](https://github.com/ember-cli/ember-cli/blob/807f56e2e434f716757de02fd1f2c3251dadaf6f/lib/broccoli/default-packager.js#L236-L261)` method.

What happens there is that `applyCustomTransforms` takes the original tree, does some transforms (I think it's mainly there to process AMD modules), whereas `processJavaScript` takes the merged tree and does all the pre- and postprocessing (including the part in `ember-cli-conditional-compile that is supposed to remove the module, but also doing the module wrapping), and when the result of those two calls gets merged, as the file is removed, it gets replaced by the unprocessed version of the module - if the module would not be removed, it would (as it's precedence is higher) replace the unprocessed version during the `mergeTrees` call.

I *think* this is an ember-cli bug?

**Comment by tehmaestro** [comment] 2019-12-01 17:19
Hi, I encountered the same problem. I opened an issue on ember-cli.

**Comment by oscarni** [comment] 2020-10-01 10:05
Encountered the same problem after upgrading from Ember `3.17` to `3.21`. The unprocessed version of the initializer is included in the production build resulting in error `Uncaught SyntaxError: Unexpected token 'export'`.

Removing https://github.com/minichate/ember-cli-conditional-compile/blob/master/index.js#L114-L118 this first part of this if-statement makes the build load. The initializer in included in the production build, but at least it still works.

(Should mention that I also had this similar issue when upgrading to Ember 3.4. But I do recall that `ember-cli-conditional-compile` `1.1.1` fixed it.)

**Closed** 2022-09-13 12:09 UTC
